service: robinhood-for-reddit

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  region: us-east-1
  stage: ${opt:stage, 'local'}
  timeout: 30
  versionFunctions: true

custom:
  localstack:
    stages:
      - local

plugins:
  - serverless-plugin-typescript
  - serverless-localstack
  - serverless-offline

functions:
  # api gateway
  hotStockHandler: ${file(./handlers/hotStock/hotStockHandler.yml):hotStockHandler}
